### ISSUE TITLE
程序运行路径含 “#” 时启动后仅显示白屏

### ISSUE THREAD

**Issue by lhyzf** [BillGoldenWater/ChaosDanmuTool#4]
系统为 Windows 11 22H2
程序为 [ChaosDanmuTool-win32-x64-0.9.1.zip](https://github.com/BillGoldenWater/ChaosDanmuTool/releases/download/0.9.1/ChaosDanmuTool-win32-x64-0.9.1.zip)

**Comment by BillGoldenWater** [comment]
可以尝试一下 [Actions](https://github.com/BillGoldenWater/ChaosDanmuTool/actions/runs/4256195795) 里正在开发的版本 底下 out 里 如果没问题的话等新版本就好了
